Config now taken from environment variables
Also, set execute permission on cgi scripts.

diff --git a/scripts/run-dev-brdf b/scripts/run-dev-brdf
--- a/scripts/run-dev-brdf
+++ b/scripts/run-dev-brdf
@@ -8,22 +8,29 @@ htmldir=$PWD/html
 python_package_src=$PWD/python-packages
 python_package_dst=/usr/lib/python2.7/site-packages
 
-check_exists() {
-    test -r "$1" || {
-        echo >&2 "`basename $0`: can't find $1"
+# check directories exist
+for dir in $caddyfile $cgidir $htmldir $python_package_src; do
+    test -r $dir || {
+        echo >&2 "`basename $0`: can't find $dir"
         echo >&2 "run this script from the toplevel repo directory"
         exit 1
     }
-}
+done
 
-for dir in $caddyfile $cgidir $htmldir $python_package_src; do
-    check_exists $dir
+# check environment variables are set
+for e in BRDF_DATABASE BRDF_DATABASE_USER BRDF_DATABASE_PASSWORD; do
+    test -n "${!e}" || {
+        echo >&2 "`basename $0`: missing required environment variable $e"
+        exit 1
+    }
 done
 
 caddyport=$((10000 + $UID))
-sitepackages=
 docker run --rm \
        --name brdf-$USER \
+       --tmpfs /tmp \
+       --tmpfs /srv/html/tmp \
+       --tmpfs /var/log \
        --tmpfs /etc/caddycerts \
        --tmpfs /root/.caddy \
        --mount type=bind,src=$caddyfile,dst=/etc/Caddyfile \
@@ -31,6 +38,27 @@ docker run --rm \
        --mount type=bind,src=$htmldir,dst=/srv/html \
        --mount type=bind,src=$python_package_src/brdf.pth,dst=$python_package_dst/brdf.pth \
        --mount type=bind,src=$python_package_src/brdf,dst=$python_package_dst/brdf \
-       --tmpfs /srv/html/tmp \
+       -e BRDF_DATABASE="$BRDF_DATABASE" \
+       -e BRDF_DATABASE_USER="$BRDF_DATABASE_USER" \
+       -e BRDF_DATABASE_PASSWORD="$BRDF_DATABASE_PASSWORD" \
+       -e BRDF_CGIPATH=cgi-bin \
+       -e BRDF_IMAGEFILEPATH=/tmp \
+       -e BRDF_IMAGEFILEPATH_AGBRDF=/srv/html/tmp \
+       -e BRDF_IMAGEURLPATH_AGBRDF=tmp \
+       -e BRDF_LOGPATH=/var/log \
+       -e BRDF_AGRESEARCH_TRACEDIRECTORY_GET_PATH='\\impala\agbrdfsequencesubmissiondev' \
+       -e BRDF_AGRESEARCH_CREATE_FOLDER_SCRIPT=/usr/local/bin/makeseqsubfolder.sh \
+       -e BRDF_BFILE_TEMPFOLDER=/srv/html/tmp \
+       -e BRDF_BFILE_TEMPURLPATH=/tmp \
+       -e BRDF_BFILE_PUTPATH=/data/databases/flatfile/uploads/agbrdf \
+       -e BRDF_BFILE_GETPATH='/cgi-bin/getFile.py?FolderName=%s' \
+       -e BRDF_CSS=/css/brdf.css \
        -p $caddyport:80 \
        agresearch/brdf
+
+# Notes:
+# - BRDF_AGRESEARCH_TRACEDIRECTORY_GET_PATH is surely not required, as the path is obsolete
+# - BRDF_AGRESEARCH_CREATE_FOLDER_SCRIPT same, the path doesn't exist on invincible
+# - BRDF_BFILE_PUTPATH same, the path doesn't exist on invincible
+# - BRDF_BFILE_GETPATH was '/cgi-bin/agbrdf/getFile.py?FolderName=%s' but that path doesn't work
+
